<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="7001" started-at="2020-06-04T00:45:15 IST" finished-at="2020-06-04T00:45:22 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="7001" started-at="2020-06-04T00:45:15 IST" finished-at="2020-06-04T00:45:22 IST">
      <class name="automation.palatable.TestCases.TestCase_Sample001">
        <test-method status="PASS" signature="setUp()[pri:0, instance:automation.palatable.TestCases.TestCase_Sample001@d44fc21]" name="setUp" is-config="true" duration-ms="21283" started-at="2020-06-04T00:44:54 IST" finished-at="2020-06-04T00:45:15 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:automation.palatable.TestCases.TestCase_Sample001@d44fc21]" name="beforeTest" is-config="true" duration-ms="4529" started-at="2020-06-04T00:45:15 IST" finished-at="2020-06-04T00:45:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="forgotPasswordButtonExistance()[pri:0, instance:automation.palatable.TestCases.TestCase_Sample001@d44fc21]" name="forgotPasswordButtonExistance" duration-ms="1112" started-at="2020-06-04T00:45:20 IST" finished-at="2020-06-04T00:45:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forgotPasswordButtonExistance -->
        <test-method status="FAIL" signature="sendButtonExistance()[pri:0, instance:automation.palatable.TestCases.TestCase_Sample001@d44fc21]" name="sendButtonExistance" duration-ms="601" started-at="2020-06-04T00:45:21 IST" finished-at="2020-06-04T00:45:22 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Send button does not exists did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Send button does not exists did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at automation.palatable.TestCases.TestCase_Sample001.sendButtonExistance(TestCase_Sample001.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendButtonExistance -->
        <test-method status="PASS" signature="verifyButtonExistance()[pri:0, instance:automation.palatable.TestCases.TestCase_Sample001@d44fc21]" name="verifyButtonExistance" duration-ms="719" started-at="2020-06-04T00:45:22 IST" finished-at="2020-06-04T00:45:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyButtonExistance -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:automation.palatable.TestCases.TestCase_Sample001@d44fc21]" name="tearDown" is-config="true" duration-ms="581" started-at="2020-06-04T00:45:27 IST" finished-at="2020-06-04T00:45:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automation.palatable.TestCases.TestCase_Sample001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
